import React, { useState, useRef } from 'react';
import { Edit2, Trash2, Camera, Plus, Loader2, ArrowLeft, Check, X, Wand2 } from 'lucide-react';
import { FoodItem, MealEntry } from '../types';
import { api } from '../services/api';

interface RecordScreenProps {
  onSave: (entry: MealEntry) => void;
}

const RecordScreen: React.FC<RecordScreenProps> = ({ onSave }) => {
  // State
  const [image, setImage] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [foodItems, setFoodItems] = useState<FoodItem[]>([]);
  const [mealType, setMealType] = useState<'Breakfast'|'Lunch'|'Dinner'|'Snack'>('Lunch');
  const [showMealSelector, setShowMealSelector] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  
  // Edit Modal State
  const [editingItem, setEditingItem] = useState<FoodItem | null>(null);
  const [isCalculatingItem, setIsCalculatingItem] = useState(false);
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Handlers
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = reader.result as string;
        setImage(base64);
        performAnalysis(base64);
      };
      reader.readAsDataURL(file);
    }
  };

  const performAnalysis = async (base64Image: string) => {
    setIsAnalyzing(true);
    try {
      const result = await api.ai.analyzeImage(base64Image);
      const items: FoodItem[] = result.map((item: any, index: number) => ({
        id: Date.now().toString() + index,
        name: item.name || '未知食物',
        portion: item.portion || '1份',
        calories: item.calories || 0,
        protein: item.protein || 0,
        carbs: item.carbs || 0,
        fat: item.fat || 0
      }));
      setFoodItems(items);
    } catch (error: any) {
      console.error('Analysis failed', error);
      setFoodItems([]);
      const errorMsg = error?.message || '未知錯誤';
      
      // Special handling for quota exceeded
      if (errorMsg.includes('配額') || errorMsg.includes('quota') || errorMsg.includes('429')) {
        alert(`分析失敗：API 配額已用盡\n\n${errorMsg}\n\n解決方法：\n1. 檢查您的 Google Gemini API 配額\n2. 等待配額重置（通常是每分鐘/每小時/每天）\n3. 升級您的 API 計劃以獲得更高配額\n\n查看配額使用情況：\nhttps://ai.dev/usage?tab=rate-limit`);
      } else {
        alert(`分析失敗：${errorMsg}\n\n請確認：\n1. 已登入帳號\n2. 後端伺服器正在運行\n3. API Key 已正確設定`);
      }
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleRemoveItem = (id: string) => {
    setFoodItems(prev => prev.filter(item => item.id !== id));
  };

  const handleAddItem = () => {
    const newItem: FoodItem = {
      id: Date.now().toString(),
      name: '',
      portion: '1份',
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0
    };
    setEditingItem(newItem);
  };

  const handleEditItem = (item: FoodItem) => {
    setEditingItem({ ...item });
  };

  const saveEditedItem = async () => {
    if (!editingItem) return;
    if (!editingItem.name.trim()) {
      alert("請輸入食物名稱");
      return;
    }

    setIsCalculatingItem(true);

    try {
      const nutrition = await api.ai.estimateNutrition(editingItem.name, editingItem.portion);
      
      const updatedItem: FoodItem = {
        ...editingItem,
        calories: nutrition.calories || 0,
        protein: nutrition.protein || 0,
        carbs: nutrition.carbs || 0,
        fat: nutrition.fat || 0
      };

      setFoodItems(prev => {
        const exists = prev.find(p => p.id === updatedItem.id);
        if (exists) {
          return prev.map(p => p.id === updatedItem.id ? updatedItem : p);
        } else {
          return [...prev, updatedItem];
        }
      });
      setEditingItem(null);
    } catch (error: any) {
      console.error("Failed to update item nutrition", error);
      const errorMsg = error?.message || '未知錯誤';
      alert(`計算營養資訊失敗：${errorMsg}\n\n請確認後端伺服器正在運行且 API Key 已正確設定`);
    } finally {
      setIsCalculatingItem(false);
    }
  };

  const calculateTotal = () => {
    return foodItems.reduce((sum, item) => sum + item.calories, 0);
  };

  const handleSave = async () => {
    if (foodItems.length === 0 || isSaving) return;

    setIsSaving(true);
    try {
    const totalCalories = calculateTotal();
    const title = foodItems.map(f => f.name).slice(0, 3).join(', ') + (foodItems.length > 3 ? '...' : '');
    const description = foodItems.map(f => f.name).join(', ');
    const now = new Date();
    const timeString = `上午${now.getHours() % 12 || 12}:${now.getMinutes().toString().padStart(2, '0')}`;
    
    const newEntry: MealEntry = {
      id: '', // ID generated by backend
      date: now.toISOString().split('T')[0],
      type: mealType,
      title: title || '自訂餐點',
      description: description,
      calories: totalCalories,
      time: timeString,
      imageUrl: image || 'https://via.placeholder.com/200?text=Food',
      ingredients: foodItems
    };

      await onSave(newEntry);
    } catch (error: any) {
      console.error('Save failed', error);
      alert(`儲存失敗：${error?.message || '未知錯誤'}\n\n請確認：\n1. 已登入帳號\n2. 後端伺服器正在運行`);
    } finally {
      setIsSaving(false);
    }
  };

  // 1. Initial State: Upload
  if (!image) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-6 pb-24 bg-white">
        <div className="mb-8 text-center">
          <h2 className="text-2xl font-bold text-gray-800 mb-2">紀錄你的每一餐</h2>
          <p className="text-gray-500">拍照或上傳圖片，AI 為你自動計算熱量</p>
        </div>

        <div 
          onClick={() => fileInputRef.current?.click()}
          className="w-64 h-64 bg-gray-50 border-2 border-dashed border-green-300 rounded-3xl flex flex-col items-center justify-center cursor-pointer hover:bg-green-50 transition-colors"
        >
          <div className="w-20 h-20 bg-green-100 text-green-600 rounded-full flex items-center justify-center mb-4">
            <Camera size={40} />
          </div>
          <span className="font-bold text-green-600">拍照或上傳</span>
        </div>
        
        <input 
          type="file" 
          ref={fileInputRef} 
          className="hidden" 
          accept="image/*" 
          onChange={handleImageUpload} 
        />
      </div>
    );
  }

  // 2. Loading State
  if (isAnalyzing) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-6 bg-white">
        <div className="w-48 h-48 mb-8 relative">
          <img src={image} alt="Analyzing" className="w-full h-full object-cover rounded-2xl opacity-50" />
          <div className="absolute inset-0 flex items-center justify-center">
            <Loader2 className="w-12 h-12 text-green-600 animate-spin" />
          </div>
        </div>
        <h2 className="text-xl font-bold text-gray-800 mb-2">AI 營養師分析中...</h2>
        <p className="text-gray-500">正在識別食材與估算份量</p>
      </div>
    );
  }

  // 3. Result / Edit State
  return (
    <div className="p-4 pb-24 bg-gray-50 min-h-full relative">
      <div className="flex justify-between items-center mb-6">
        <div className="flex items-center gap-2">
           <button onClick={() => setImage(null)} className="p-2 hover:bg-gray-200 rounded-full">
             <ArrowLeft size={20} className="text-gray-600"/>
           </button>
           <h2 className="text-2xl font-bold text-gray-800">分析結果</h2>
        </div>
        <div className="relative">
          <button 
            onClick={() => setShowMealSelector(!showMealSelector)}
            className="px-4 py-1.5 bg-white border border-gray-200 rounded-lg text-sm font-medium text-gray-600 shadow-sm flex items-center gap-2"
          >
            {mealType === 'Breakfast' && '早餐'}
            {mealType === 'Lunch' && '午餐'}
            {mealType === 'Dinner' && '晚餐'}
            {mealType === 'Snack' && '點心'}
            <span>▾</span>
          </button>
          {showMealSelector && (
            <div className="absolute right-0 top-full mt-2 w-32 bg-white rounded-lg shadow-xl border border-gray-100 z-10 overflow-hidden">
              {['Breakfast', 'Lunch', 'Dinner', 'Snack'].map((type) => (
                <button
                  key={type}
                  onClick={() => {
                    setMealType(type as any);
                    setShowMealSelector(false);
                  }}
                  className="w-full text-left px-4 py-2 text-sm hover:bg-green-50 text-gray-700"
                >
                   {type === 'Breakfast' && '早餐'}
                   {type === 'Lunch' && '午餐'}
                   {type === 'Dinner' && '晚餐'}
                   {type === 'Snack' && '點心'}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
      
      <div className="mb-6 w-full h-48 rounded-2xl overflow-hidden shadow-md relative">
        <img src={image} alt="Food" className="w-full h-full object-cover" />
        <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/60 to-transparent p-4">
          <div className="text-white">
            <span className="text-sm font-medium opacity-90">總熱量預估</span>
            <div className="text-3xl font-bold">{calculateTotal()} <span className="text-lg font-normal">kcal</span></div>
          </div>
        </div>
      </div>

      <div className="space-y-4">
        {foodItems.map((item) => (
          <div key={item.id} className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
            <div className="flex justify-between items-start mb-2">
              <div>
                <h3 className="text-lg font-bold text-gray-800">{item.name}</h3>
              </div>
              <div className="flex gap-3">
                <button 
                  onClick={() => handleEditItem(item)}
                  className="p-1.5 bg-green-50 rounded-full text-green-600 hover:bg-green-100"
                >
                  <Edit2 size={16} />
                </button>
              </div>
            </div>

            <div className="flex justify-between items-end mb-4">
              <div className="border-b border-gray-200 pb-1 w-1/2">
                 <span className="text-sm text-gray-500 block mb-1">份量</span>
                 <span className="text-gray-700">{item.portion}</span>
              </div>
              <div className="text-right flex items-end gap-4">
                <div>
                    <span className="text-xs text-gray-400 block mb-1">熱量 (kcal)</span>
                    <span className="text-2xl font-bold text-green-600">{item.calories}</span>
                </div>
                 <button 
                  onClick={() => handleRemoveItem(item.id)}
                  className="p-1.5 text-gray-400 hover:text-red-500 mb-1"
                 >
                  <Trash2 size={18} />
                </button>
              </div>
            </div>
          </div>
        ))}

        <button 
          onClick={handleAddItem}
          className="w-full py-3 border-2 border-dashed border-gray-300 rounded-xl text-gray-500 font-medium flex items-center justify-center gap-2 hover:bg-gray-50 transition-colors"
        >
          <Plus size={20} />
          新增品項
        </button>
      </div>

      <div className="fixed bottom-20 left-0 right-0 px-4 pb-4 bg-gradient-to-t from-gray-50 via-gray-50 to-transparent pt-8 z-10 max-w-md mx-auto pointer-events-none">
        <button 
          onClick={handleSave}
          disabled={isSaving || foodItems.length === 0}
          className="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-4 rounded-xl shadow-lg shadow-green-200 transition-transform active:scale-[0.98] flex items-center justify-center gap-2 pointer-events-auto disabled:opacity-70 disabled:cursor-not-allowed disabled:active:scale-100"
        >
          {isSaving ? (
            <>
              <Loader2 size={20} className="animate-spin" />
              <span>儲存中...</span>
            </>
          ) : (
            <>
          <Check size={20} />
              <span>確認並儲存至日記</span>
            </>
          )}
        </button>
      </div>

      {editingItem && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
           <div className="bg-white w-full max-w-sm rounded-2xl p-6 shadow-2xl relative overflow-hidden">
              {isCalculatingItem && (
                <div className="absolute inset-0 bg-white/80 backdrop-blur-[1px] z-10 flex flex-col items-center justify-center">
                   <Loader2 className="w-10 h-10 text-green-600 animate-spin mb-2" />
                   <p className="text-green-600 font-medium text-sm">AI 重新計算營養中...</p>
                </div>
              )}

              <div className="flex justify-between items-center mb-6">
                 <h3 className="text-xl font-bold text-gray-800">
                   {foodItems.find(i => i.id === editingItem.id) ? '編輯品項' : '新增品項'}
                 </h3>
                 <button 
                   onClick={() => setEditingItem(null)} 
                   disabled={isCalculatingItem}
                   className="p-2 bg-gray-100 rounded-full hover:bg-gray-200 disabled:opacity-50"
                 >
                    <X size={20} className="text-gray-600" />
                 </button>
              </div>

              <div className="space-y-6">
                 <div>
                   <label className="block text-sm font-bold text-gray-700 mb-2">食物名稱</label>
                   <input 
                     type="text"
                     value={editingItem.name}
                     onChange={(e) => setEditingItem({...editingItem, name: e.target.value})}
                     className="w-full p-3.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-green-500 outline-none bg-gray-50 text-gray-900"
                     placeholder="例如：雞胸肉"
                   />
                 </div>
                 
                 <div>
                    <label className="block text-sm font-bold text-gray-700 mb-2">份量描述</label>
                    <input 
                      type="text"
                      value={editingItem.portion}
                      onChange={(e) => setEditingItem({...editingItem, portion: e.target.value})}
                      className="w-full p-3.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-green-500 outline-none bg-gray-50 text-gray-900"
                      placeholder="例如：100g 或 1塊"
                    />
                 </div>
              </div>

              <div className="mt-8">
                <button 
                  onClick={saveEditedItem}
                  disabled={isCalculatingItem}
                  className="w-full bg-green-600 text-white font-bold py-3.5 rounded-xl shadow-lg shadow-green-100 hover:bg-green-700 active:scale-[0.98] transition-all flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
                >
                  <Wand2 size={18} />
                  更新並計算熱量
                </button>
              </div>
           </div>
        </div>
      )}
    </div>
  );
};

export default RecordScreen;